name = "atlasquizbotpro"
main = "worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "atlasbot-db"
database_id = "9b866cf1-d4e8-440c-a2f8-33f2b826e383"

[triggers]
crons = ["*/15 * * * *"]
